"""Builds the thermal-printer (1-bit raster) version of the real brand logo.

Source: apps/web/public/logo-512.png (the owner's MY FOOD / Chefelisha artwork, cut to its circle).
Output: packages/escpos/src/logo.ts  (width 256 dots, MSB-first rows, 1 = black), used by GS v 0.
Run:    python3 scripts/brand/make-receipt-logo.py
"""
import base64
from PIL import Image

SIZE = 256
img = Image.open('apps/web/public/logo-512.png').convert('RGBA').resize((SIZE, SIZE), Image.LANCZOS)
bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
gray = Image.alpha_composite(bg, img).convert('L')
bits = bytearray()
for y in range(SIZE):
    for xb in range(SIZE // 8):
        byte = 0
        for i in range(8):
            if gray.getpixel((xb * 8 + i, y)) < 170:
                byte |= 0x80 >> i
        bits.append(byte)
data = base64.b64encode(bytes(bits)).decode()
with open('packages/escpos/src/logo.ts', 'w') as f:
    f.write('// GENERATED by scripts/brand/make-receipt-logo.py from apps/web/public/logo-512.png. Do not edit.\n')
    f.write(f'export const LOGO_WIDTH = {SIZE};\nexport const LOGO_HEIGHT = {SIZE};\n')
    f.write(f"export const LOGO_BITS_BASE64 =\n  '{data}';\n")
print('bytes', len(bits))
