import { ListActivity } from './use-cases/activity';
import {
  ApproveDevicePairing,
  CollectDevicePairing,
  CreatePairingCode,
  CreateStaff,
  DeleteConfig,
  GetConfiguration,
  PairDevice,
  RegisterPersonalDevice,
  RequestDevicePairing,
  RevokeDevice,
  SaveConfig,
  UpdateStaff,
} from './use-cases/administration';
import {
  CreateCustomer,
  GetCustomer,
  ListCustomers,
  LookupCustomer,
  MergeCustomer,
  SetOrderCustomer,
  UpdateCustomer,
} from './use-cases/customers';
import { GetHubSnapshot, IngestHubBatch, SetBranchHub } from './use-cases/hub-sync';
import {
  ApproveStockCount,
  CancelStockCount,
  GetRecipe,
  GetStockCount,
  ListInventory,
  ListStockCounts,
  ListStockMovements,
  RecordCountLine,
  RecordStockMovement,
  SaveInventoryItem,
  SaveRecipe,
  StartStockCount,
  SubmitStockCount,
} from './use-cases/inventory';
import { FulfilOrder, MarkOrderReady, TransitionTicket } from './use-cases/kitchen';
import { AcceptOwnerInvitation, SendSignInLink, StartOwnerOnboarding } from './use-cases/onboarding';
import { GetDashboard, GetExpoBoard, GetSalesReport } from './use-cases/operations';
import {
  CancelOrder,
  GetBill,
  GetReceipt,
  PrintReceipt,
  RequestBill,
  VoidItems,
} from './use-cases/order-corrections';
import { SendOrderToKitchen, SubmitOrder } from './use-cases/orders';
import { RecordPayment, RefundPayment, VoidPayment } from './use-cases/payments';
import {
  AssignStaffPin,
  ChangeOwnPin,
  ChangePinFromHub,
  PinSignIn,
  RequestPinRecovery,
  SignInWithEmailAndPin,
  VerifyPinForHub,
} from './use-cases/pins';
import {
  ClaimPrintJobs,
  GetAgentConfig,
  GetPrintQueue,
  ReportPrintJobResult,
  RetryPrintJob,
  SendTestPrint,
} from './use-cases/printing';
import { RemoveProductImage, SetProductImage, SetProductImageThumb } from './use-cases/product-images';
import {
  ApplyManualDiscount,
  ListPromotions,
  PreviewPromotion,
  RemoveManualDiscount,
  SavePromotion,
  SetPromotionStatus,
} from './use-cases/promotions';
import {
  GetCustomerBoard,
  GetOrder,
  GetStationBoard,
  ListActiveOrders,
  ListRecentClosedOrders,
  RecordHeartbeat,
} from './use-cases/queries';
import {
  CloseRegister,
  GetCurrentRegister,
  GetRegister,
  ListRegisters,
  OpenRegister,
  ReopenRegister,
} from './use-cases/registers';
import {
  ExportReport,
  GetRegisterClosingReport,
  GetReport,
  GetReportFilterOptions,
} from './use-cases/reports';
import { GetFloor, GetMe, GetMenu, GetOperationsStatus, SetTableStatus } from './use-cases/session';
import type { Dependencies } from './use-cases/shared';
import { MergeOrders, SetOrderPriority, TransferOrder } from './use-cases/table-ops';

export * from './ports';
export * from './principal';
export { REPORT_TITLES } from './use-cases/reports';
export type { Dependencies } from './use-cases/shared';

export function createApplication(deps: Dependencies) {
  return {
    submitOrder: new SubmitOrder(deps),
    sendOrderToKitchen: new SendOrderToKitchen(deps),
    transitionTicket: new TransitionTicket(deps),
    fulfilOrder: new FulfilOrder(deps),
    recordPayment: new RecordPayment(deps),
    voidPayment: new VoidPayment(deps),
    refundPayment: new RefundPayment(deps),
    getAgentConfig: new GetAgentConfig(deps),
    claimPrintJobs: new ClaimPrintJobs(deps),
    reportPrintJobResult: new ReportPrintJobResult(deps),
    retryPrintJob: new RetryPrintJob(deps),
    getPrintQueue: new GetPrintQueue(deps),
    sendTestPrint: new SendTestPrint(deps),
    getHubSnapshot: new GetHubSnapshot(deps),
    ingestHubBatch: new IngestHubBatch(deps),
    setBranchHub: new SetBranchHub(deps),
    verifyPinForHub: new VerifyPinForHub(deps),
    changePinFromHub: new ChangePinFromHub(deps),
    getOrder: new GetOrder(deps),
    listActiveOrders: new ListActiveOrders(deps),
    listRecentClosedOrders: new ListRecentClosedOrders(deps),
    getDashboard: new GetDashboard(deps),
    getExpoBoard: new GetExpoBoard(deps),
    getSalesReport: new GetSalesReport(deps),
    transferOrder: new TransferOrder(deps),
    mergeOrders: new MergeOrders(deps),
    setOrderPriority: new SetOrderPriority(deps),
    pinSignIn: new PinSignIn(deps),
    signInWithEmailAndPin: new SignInWithEmailAndPin(deps),
    changeOwnPin: new ChangeOwnPin(deps),
    assignStaffPin: new AssignStaffPin(deps),
    requestPinRecovery: new RequestPinRecovery(deps),
    listInventory: new ListInventory(deps),
    listStockMovements: new ListStockMovements(deps),
    saveInventoryItem: new SaveInventoryItem(deps),
    recordStockMovement: new RecordStockMovement(deps),
    listStockCounts: new ListStockCounts(deps),
    getStockCount: new GetStockCount(deps),
    startStockCount: new StartStockCount(deps),
    recordCountLine: new RecordCountLine(deps),
    submitStockCount: new SubmitStockCount(deps),
    approveStockCount: new ApproveStockCount(deps),
    cancelStockCount: new CancelStockCount(deps),
    getRecipe: new GetRecipe(deps),
    saveRecipe: new SaveRecipe(deps),
    getStationBoard: new GetStationBoard(deps),
    getCustomerBoard: new GetCustomerBoard(deps),
    recordHeartbeat: new RecordHeartbeat(deps),
    markOrderReady: new MarkOrderReady(deps),
    cancelOrder: new CancelOrder(deps),
    voidItems: new VoidItems(deps),
    getReceipt: new GetReceipt(deps),
    printReceipt: new PrintReceipt(deps),
    getBill: new GetBill(deps),
    requestBill: new RequestBill(deps),
    getMe: new GetMe(deps),
    getMenu: new GetMenu(deps),
    getFloor: new GetFloor(deps),
    setTableStatus: new SetTableStatus(deps),
    getOperationsStatus: new GetOperationsStatus(deps),
    getConfiguration: new GetConfiguration(deps),
    saveConfig: new SaveConfig(deps),
    deleteConfig: new DeleteConfig(deps),
    createStaff: new CreateStaff(deps),
    updateStaff: new UpdateStaff(deps),
    createPairingCode: new CreatePairingCode(deps),
    pairDevice: new PairDevice(deps),
    requestDevicePairing: new RequestDevicePairing(deps),
    approveDevicePairing: new ApproveDevicePairing(deps),
    collectDevicePairing: new CollectDevicePairing(deps),
    revokeDevice: new RevokeDevice(deps),
    listActivity: new ListActivity(deps),
    startOwnerOnboarding: new StartOwnerOnboarding(deps),
    acceptOwnerInvitation: new AcceptOwnerInvitation(deps),
    sendSignInLink: new SendSignInLink(deps),
    registerPersonalDevice: new RegisterPersonalDevice(deps),
    setProductImage: new SetProductImage(deps),
    setProductImageThumb: new SetProductImageThumb(deps),
    removeProductImage: new RemoveProductImage(deps),
    listPromotions: new ListPromotions(deps),
    previewPromotion: new PreviewPromotion(deps),
    savePromotion: new SavePromotion(deps),
    setPromotionStatus: new SetPromotionStatus(deps),
    applyManualDiscount: new ApplyManualDiscount(deps),
    removeManualDiscount: new RemoveManualDiscount(deps),
    listCustomers: new ListCustomers(deps),
    getCustomer: new GetCustomer(deps),
    lookupCustomer: new LookupCustomer(deps),
    createCustomer: new CreateCustomer(deps),
    updateCustomer: new UpdateCustomer(deps),
    mergeCustomer: new MergeCustomer(deps),
    setOrderCustomer: new SetOrderCustomer(deps),
    openRegister: new OpenRegister(deps),
    getCurrentRegister: new GetCurrentRegister(deps),
    getRegister: new GetRegister(deps),
    listRegisters: new ListRegisters(deps),
    closeRegister: new CloseRegister(deps),
    reopenRegister: new ReopenRegister(deps),
    getReport: new GetReport(deps),
    getReportFilterOptions: new GetReportFilterOptions(deps),
    exportReport: new ExportReport(deps),
    getRegisterClosingReport: new GetRegisterClosingReport(deps),
  };
}
export type Application = ReturnType<typeof createApplication>;
